// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cybersecurity/threatintel/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69c11b38a4269049, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69c11b38a4269049, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryListThreatReportsRequest defines the QueryListThreatReportsRequest message.
type QueryListThreatReportsRequest struct {
}

func (m *QueryListThreatReportsRequest) Reset()         { *m = QueryListThreatReportsRequest{} }
func (m *QueryListThreatReportsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListThreatReportsRequest) ProtoMessage()    {}
func (*QueryListThreatReportsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69c11b38a4269049, []int{2}
}
func (m *QueryListThreatReportsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListThreatReportsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListThreatReportsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListThreatReportsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListThreatReportsRequest.Merge(m, src)
}
func (m *QueryListThreatReportsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListThreatReportsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListThreatReportsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListThreatReportsRequest proto.InternalMessageInfo

// QueryListThreatReportsResponse defines the QueryListThreatReportsResponse message.
type QueryListThreatReportsResponse struct {
	Reports string `protobuf:"bytes,1,opt,name=reports,proto3" json:"reports,omitempty"`
}

func (m *QueryListThreatReportsResponse) Reset()         { *m = QueryListThreatReportsResponse{} }
func (m *QueryListThreatReportsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListThreatReportsResponse) ProtoMessage()    {}
func (*QueryListThreatReportsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69c11b38a4269049, []int{3}
}
func (m *QueryListThreatReportsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListThreatReportsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListThreatReportsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListThreatReportsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListThreatReportsResponse.Merge(m, src)
}
func (m *QueryListThreatReportsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListThreatReportsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListThreatReportsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListThreatReportsResponse proto.InternalMessageInfo

func (m *QueryListThreatReportsResponse) GetReports() string {
	if m != nil {
		return m.Reports
	}
	return ""
}

type QueryListMaliciousIpsRequest struct {
}

func (m *QueryListMaliciousIpsRequest) Reset()         { *m = QueryListMaliciousIpsRequest{} }
func (m *QueryListMaliciousIpsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListMaliciousIpsRequest) ProtoMessage()    {}
func (*QueryListMaliciousIpsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69c11b38a4269049, []int{4}
}
func (m *QueryListMaliciousIpsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListMaliciousIpsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListMaliciousIpsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListMaliciousIpsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListMaliciousIpsRequest.Merge(m, src)
}
func (m *QueryListMaliciousIpsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListMaliciousIpsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListMaliciousIpsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListMaliciousIpsRequest proto.InternalMessageInfo

type QueryListMaliciousIpsResponse struct {
	Ips []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (m *QueryListMaliciousIpsResponse) Reset()         { *m = QueryListMaliciousIpsResponse{} }
func (m *QueryListMaliciousIpsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListMaliciousIpsResponse) ProtoMessage()    {}
func (*QueryListMaliciousIpsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69c11b38a4269049, []int{5}
}
func (m *QueryListMaliciousIpsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListMaliciousIpsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListMaliciousIpsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListMaliciousIpsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListMaliciousIpsResponse.Merge(m, src)
}
func (m *QueryListMaliciousIpsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListMaliciousIpsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListMaliciousIpsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListMaliciousIpsResponse proto.InternalMessageInfo

func (m *QueryListMaliciousIpsResponse) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cybersecurity.threatintel.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cybersecurity.threatintel.v1.QueryParamsResponse")
	proto.RegisterType((*QueryListThreatReportsRequest)(nil), "cybersecurity.threatintel.v1.QueryListThreatReportsRequest")
	proto.RegisterType((*QueryListThreatReportsResponse)(nil), "cybersecurity.threatintel.v1.QueryListThreatReportsResponse")
	proto.RegisterType((*QueryListMaliciousIpsRequest)(nil), "cybersecurity.threatintel.v1.QueryListMaliciousIpsRequest")
	proto.RegisterType((*QueryListMaliciousIpsResponse)(nil), "cybersecurity.threatintel.v1.QueryListMaliciousIpsResponse")
}

func init() {
	proto.RegisterFile("cybersecurity/threatintel/v1/query.proto", fileDescriptor_69c11b38a4269049)
}

var fileDescriptor_69c11b38a4269049 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x41, 0x6b, 0x14, 0x31,
	0x18, 0xdd, 0x58, 0x5d, 0xd9, 0x78, 0x69, 0x63, 0x0f, 0x65, 0x58, 0x53, 0x1d, 0x8a, 0xac, 0x45,
	0x26, 0x9d, 0xed, 0x45, 0xbb, 0x9e, 0x7a, 0x11, 0x41, 0x41, 0x07, 0x4f, 0x1e, 0x5c, 0xb2, 0x4b,
	0x18, 0x03, 0xbb, 0x93, 0x34, 0xc9, 0x2c, 0xce, 0xd5, 0x5f, 0x20, 0x78, 0xf4, 0x0f, 0x78, 0xf4,
	0xea, 0x0f, 0x10, 0xea, 0xad, 0xe0, 0xc5, 0x93, 0xc8, 0xae, 0xe0, 0xdf, 0x90, 0x49, 0xd2, 0xa5,
	0x63, 0xed, 0x30, 0xdd, 0xcb, 0xf0, 0xcd, 0x37, 0xef, 0xbd, 0xef, 0xbd, 0x7c, 0x13, 0xd8, 0x1b,
	0x17, 0x23, 0xa6, 0x34, 0x1b, 0xe7, 0x8a, 0x9b, 0x82, 0x98, 0x37, 0x8a, 0x51, 0xc3, 0x33, 0xc3,
	0x26, 0x64, 0x16, 0x93, 0xa3, 0x9c, 0xa9, 0x22, 0x92, 0x4a, 0x18, 0x81, 0xba, 0x15, 0x64, 0x74,
	0x06, 0x19, 0xcd, 0xe2, 0x60, 0x83, 0x4e, 0x79, 0x26, 0x88, 0x7d, 0x3a, 0x42, 0xb0, 0x3b, 0x16,
	0x7a, 0x2a, 0x34, 0x19, 0x51, 0xcd, 0x9c, 0x12, 0x99, 0xc5, 0x23, 0x66, 0x68, 0x4c, 0x24, 0x4d,
	0x79, 0x46, 0x0d, 0x17, 0x99, 0xc7, 0xde, 0xab, 0xb5, 0x21, 0xa9, 0xa2, 0x53, 0xed, 0xa1, 0x9b,
	0xa9, 0x48, 0x85, 0x2d, 0x49, 0x59, 0xf9, 0x6e, 0x37, 0x15, 0x22, 0x9d, 0x30, 0x42, 0x25, 0x27,
	0x34, 0xcb, 0x84, 0xb1, 0xea, 0x9e, 0x13, 0x6e, 0x42, 0xf4, 0xa2, 0x34, 0xf0, 0xdc, 0x0a, 0x25,
	0xec, 0x28, 0x67, 0xda, 0x84, 0xaf, 0xe1, 0xcd, 0x4a, 0x57, 0x4b, 0x91, 0x69, 0x86, 0x1e, 0xc3,
	0xb6, 0x1b, 0xb8, 0x05, 0x6e, 0x83, 0xde, 0x8d, 0xfe, 0x4e, 0x54, 0x97, 0x3c, 0x72, 0xec, 0xc3,
	0xce, 0xf1, 0xcf, 0xed, 0xd6, 0xa7, 0x3f, 0x9f, 0x77, 0x41, 0xe2, 0xe9, 0xe1, 0x36, 0xbc, 0x65,
	0xf5, 0x9f, 0x72, 0x6d, 0x5e, 0x5a, 0x52, 0xc2, 0xa4, 0x50, 0x66, 0x69, 0xe0, 0x00, 0xe2, 0x8b,
	0x00, 0xde, 0xcb, 0x16, 0xbc, 0xae, 0x5c, 0xcb, 0x9a, 0xe9, 0x24, 0xa7, 0xaf, 0x21, 0x86, 0xdd,
	0x25, 0xf7, 0x19, 0x9d, 0xf0, 0x31, 0x17, 0xb9, 0x7e, 0x22, 0x97, 0xda, 0xf1, 0x99, 0xe1, 0xd5,
	0xef, 0x5e, 0x7a, 0x1d, 0xae, 0x71, 0x59, 0xca, 0xae, 0xf5, 0x3a, 0x49, 0x59, 0xf6, 0xbf, 0x5c,
	0x85, 0xd7, 0x2c, 0x07, 0x7d, 0x04, 0xb0, 0xed, 0x72, 0xa1, 0xbd, 0xfa, 0xf4, 0xe7, 0x8f, 0x35,
	0x88, 0x2f, 0xc1, 0x70, 0x5e, 0xc2, 0xfb, 0xef, 0xbe, 0xff, 0xfe, 0x70, 0xe5, 0x2e, 0xda, 0x21,
	0x0d, 0xfe, 0x03, 0xf4, 0x0d, 0xc0, 0x8d, 0x73, 0x47, 0x86, 0x06, 0x0d, 0xc6, 0x5e, 0xb4, 0x89,
	0xe0, 0xd1, 0x6a, 0x64, 0x6f, 0xff, 0xa1, 0xb5, 0xbf, 0x8f, 0xe2, 0x7a, 0xfb, 0x13, 0xae, 0xcd,
	0xd0, 0xf5, 0x86, 0x7e, 0x8d, 0xe8, 0x2b, 0x80, 0xeb, 0xff, 0xae, 0x08, 0x1d, 0x34, 0x74, 0xf3,
	0x9f, 0xbd, 0x07, 0x83, 0x95, 0xb8, 0x3e, 0xc8, 0x03, 0x1b, 0xa4, 0x8f, 0xf6, 0x1a, 0x04, 0x99,
	0x9e, 0x0a, 0x0c, 0xb9, 0xd4, 0x87, 0x83, 0xe3, 0x39, 0x06, 0x27, 0x73, 0x0c, 0x7e, 0xcd, 0x31,
	0x78, 0xbf, 0xc0, 0xad, 0x93, 0x05, 0x6e, 0xfd, 0x58, 0xe0, 0xd6, 0xab, 0x3b, 0x55, 0xa9, 0xb7,
	0x15, 0x31, 0x53, 0x48, 0xa6, 0x47, 0x6d, 0x7b, 0x4b, 0xf7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xdb, 0x67, 0xa1, 0x3a, 0x8d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListThreatReports Queries a list of ListThreatReports items.
	ListThreatReports(ctx context.Context, in *QueryListThreatReportsRequest, opts ...grpc.CallOption) (*QueryListThreatReportsResponse, error)
	ListMaliciousIps(ctx context.Context, in *QueryListMaliciousIpsRequest, opts ...grpc.CallOption) (*QueryListMaliciousIpsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cybersecurity.threatintel.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListThreatReports(ctx context.Context, in *QueryListThreatReportsRequest, opts ...grpc.CallOption) (*QueryListThreatReportsResponse, error) {
	out := new(QueryListThreatReportsResponse)
	err := c.cc.Invoke(ctx, "/cybersecurity.threatintel.v1.Query/ListThreatReports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListMaliciousIps(ctx context.Context, in *QueryListMaliciousIpsRequest, opts ...grpc.CallOption) (*QueryListMaliciousIpsResponse, error) {
	out := new(QueryListMaliciousIpsResponse)
	err := c.cc.Invoke(ctx, "/cybersecurity.threatintel.v1.Query/ListMaliciousIps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListThreatReports Queries a list of ListThreatReports items.
	ListThreatReports(context.Context, *QueryListThreatReportsRequest) (*QueryListThreatReportsResponse, error)
	ListMaliciousIps(context.Context, *QueryListMaliciousIpsRequest) (*QueryListMaliciousIpsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ListThreatReports(ctx context.Context, req *QueryListThreatReportsRequest) (*QueryListThreatReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListThreatReports not implemented")
}
func (*UnimplementedQueryServer) ListMaliciousIps(ctx context.Context, req *QueryListMaliciousIpsRequest) (*QueryListMaliciousIpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMaliciousIps not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybersecurity.threatintel.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListThreatReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListThreatReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListThreatReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybersecurity.threatintel.v1.Query/ListThreatReports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListThreatReports(ctx, req.(*QueryListThreatReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListMaliciousIps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListMaliciousIpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListMaliciousIps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybersecurity.threatintel.v1.Query/ListMaliciousIps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListMaliciousIps(ctx, req.(*QueryListMaliciousIpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cybersecurity.threatintel.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ListThreatReports",
			Handler:    _Query_ListThreatReports_Handler,
		},
		{
			MethodName: "ListMaliciousIps",
			Handler:    _Query_ListMaliciousIps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cybersecurity/threatintel/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListThreatReportsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListThreatReportsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListThreatReportsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryListThreatReportsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListThreatReportsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListThreatReportsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reports) > 0 {
		i -= len(m.Reports)
		copy(dAtA[i:], m.Reports)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Reports)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListMaliciousIpsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListMaliciousIpsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListMaliciousIpsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryListMaliciousIpsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListMaliciousIpsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListMaliciousIpsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ips) > 0 {
		for iNdEx := len(m.Ips) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Ips[iNdEx])
			copy(dAtA[i:], m.Ips[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Ips[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListThreatReportsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryListThreatReportsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Reports)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListMaliciousIpsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryListMaliciousIpsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ips) > 0 {
		for _, s := range m.Ips {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListThreatReportsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListThreatReportsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListThreatReportsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListThreatReportsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListThreatReportsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListThreatReportsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reports", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reports = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListMaliciousIpsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListMaliciousIpsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListMaliciousIpsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListMaliciousIpsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListMaliciousIpsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListMaliciousIpsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ips", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ips = append(m.Ips, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
